plugins/xenserver/xenapi/etc/xapi.d/plugins/agent               /usr/lib/xcp/plugins
plugins/xenserver/xenapi/etc/xapi.d/plugins/glance              /usr/lib/xcp/plugins
plugins/xenserver/xenapi/etc/xapi.d/plugins/migration           /usr/lib/xcp/plugins
plugins/xenserver/xenapi/etc/xapi.d/plugins/pluginlib_nova.py   /usr/lib/xcp/plugins
plugins/xenserver/xenapi/etc/xapi.d/plugins/xenhost             /usr/lib/xcp/plugins
plugins/xenserver/xenapi/etc/xapi.d/plugins/xenstore.py         /usr/lib/xcp/plugins
