#!/bin/sh

websslpath=/usr/share/ca-certificates/contrail_webui_ssl
sslsub=/C=US/ST=CA/L=Sunnyvale/O=JuniperNetworks/OU=JuniperCA/CN=ContrailCA

if [ ! -e $websslpath/cs-key.pem ] && [ ! -e $websslpath/cs-cert.pem ]; then
	openssl req -new -newkey rsa:2048 -nodes -out $websslpath/certrequest.csr -keyout $websslpath/cs-key.pem -subj $sslsub
	openssl x509 -req -days 730 -in $websslpath/certrequest.csr -signkey $websslpath/cs-key.pem -out $websslpath/cs-cert.pem
fi
