Document: nova-docker
Title: Debian nova-docker Manual
Author: <insert document author here>
Abstract: This manual describes what nova-docker is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nova-docker/nova-docker.sgml.gz

Format: postscript
Files: /usr/share/doc/nova-docker/nova-docker.ps.gz

Format: text
Files: /usr/share/doc/nova-docker/nova-docker.text.gz

Format: HTML
Index: /usr/share/doc/nova-docker/html/index.html
Files: /usr/share/doc/nova-docker/html/*.html
