#!/bin/sh
#
# neutron  OpenStack Software Defined Networking Service
#
# chkconfig:   - 99 02
# description: neutron provides an API to  \
#		* request and configure virtual networks
### END INIT INFO

. /etc/rc.d/init.d/functions

prog=neutron
exec="/usr/bin/$prog-server"
config="/etc/$prog/$prog.conf"
pidfile="/var/run/$prog/$prog.pid"
logfile="/var/log/$prog/server.log"
plugin_config="/etc/$prog/plugins/opencontrail/ContrailPlugin.ini"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog-server

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon --user neutron --pidfile $pidfile "$exec --config-file $config --config-file ${plugin_config} --log-file $logfile &>/dev/null & echo \$! > $pidfile"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
