#!/bin/tcsh -f

if ($#argv != 1) then
   echo "Usage: add-branch <repo-list-file> \n"
   echo "<repo-list-file> should have 1 or more lines in following format:"
   echo "      <repo name> <git id> <branch name> <ci-yes | ci-no> "
   echo "Example: "
   echo "contrail-controller R1.10 ci-yes 7e97202c58cc901ecb0ae2bc0b78f39ca569ada0" 
   echo "contrail-web-core R1.10 ci-no 7e97202c58cc901ecb0ae2bc0b78f39ca569ada0"
   exit 0
endif

set tag="R2.20"
set file=$argv[1]

foreach f ( "`cat $file`" )
   set dir=`echo "$f" | awk '{print $1}'`
   set branch=`echo "$f" | awk '{print $2}'`
   set yesno=`echo "$f" | awk '{print $3}'`
   set sha=`echo "$f" | awk '{print $4}'`
   echo ">>> Working on:   $dir, $yesno"
   echo ">>> Cloning $dir ..."
   git clone git@github.com:Juniper/$dir
   cd $dir
   echo ">>> Checkout branch $branch ... "
   if ($yesno == "ci-yes") then
       git review -s
       set org="gerrit"
       git branch $branch $sha

       echo ">>> Branching repo $dir with $tag "
       echo ">>> Pushing change for review..."
       git push gerrit $branch
       git branch
       git checkout R2.20
       git branch

       cat .gitreview | sed -e "s/defaultbranch=master/defaultbranch=$branch/" > .gitreview.tmp
       \rm -f .gitreview
       mv .gitreview.tmp .gitreview
       cat .gitreview
       git commit -m "Adding R2.20 branch to CI" .
       git review
   else
       echo ">>> Branching repo $dir with $tag "
       echo ">>> Pushing change for review..."
       git checkout -b $branch $sha
       git commit -m "Adding R2.20 branch" .
       git push origin $branch
       git branch
       git checkout R2.20
       git branch
   endif

   cd -
   echo "----- \n\n"
end
