#!/usr/bin/env bash
#set -x

#################################################################################
#                                                                               #
#                      Vinay Mahuli                                             #
#                      August 2014                                              #
#                      commit-info                                              #
#                                                                               #
#       This script is used to get the list of changes submitted to github      #
#       for various repos.                                                      #
#                                                                               #
#       Dependency: getgitcommits.py                                            #
#                                                                               #
#       Output: This is a wrapper script which gives code diffs as output and   #
#               also writes it to commit-info.log file                          #
#                                                                               #
#################################################################################

export WORKSPACE="$PWD"
manifest_file="$WORKSPACE/.repo/manifest.xml"
#build_loc="/volume/contrail"
build_loc="/github-build"

if [ -L $manifest_file ]; then
    repos=`cat $manifest_file | grep "remote=\"github" | grep -v refs | awk -F "path=" '/path/ {print $2}' | sed -e 's/\"//g' | sed -e 's/\/>//' | sed -e 's/>//'`
fi

usage ()
{
    echo
    echo 'Usage 1 : ./commit-info  -release <R1.05|R1.06|R1.10|mainline> -build <bno1[,bno2]> [-os <ubuntu-12-04|centos64_os>] [-sku <havana|icehouse>]'
    echo 'Eg.       ./commit-info  -release R1.10 -build 2'
    echo
    echo 'Usage 2 : ./commit-info  -manifest <manifest1> <manifest2>'
    echo 'Eg.       ./commit-info  -manifest manifest_2304.xml manifest_2305.xml'
    echo
    exit
}

function parse_arguments() {
    while echo $1 | grep -q ^-; do
        eval $( echo $1 | sed 's/^-//' )=$2
        shift
        shift
    done

    [ "x$sku" = "x" ] && sku=havana
    [ "x$os" = "x" ] && os=ubuntu-12-04
    [ "x$release" = "x" ] && usage
    [ "x$build" = "x" ] && usage
    [ "$os" != "centos64_os" -a "$os" != "ubuntu-12-04" -a "$os" != "centos65" ] && usage
    [ "$sku" != "havana" -a "$sku" != "icehouse" ] && usage

    build1=`echo $build | cut -d ',' -f1`
    build2=`echo $build | cut -d ',' -f2`
    [ $build1 = $build2 ] && build2="LATEST"
 
    sbver=`cat $manifest_file | awk -F "revision=" '/revision/ {print $2}' | grep vrouter | cut -d ' ' -f1 | sed -e 's/\"//g'`
    [ "x$sbver" = "x" ] && sbver="mainline"
    if [ "x$sbver" != "x$release" ]; then
        echo
        echo "Release version field is incorrect!"
        echo "Your sandbox is of different version!"
        echo
        exit 1
    fi
}

function check_sb() {
    cd $WORKSPACE
    if [ ! -d controller -o ! -d vrouter -o ! -d tools -o ! -d contrail-web-core -o ! -d third_party -o ! -d openstack -o ! -d contrail-horizon ]; then
        echo "You need to run this utility from sandbox location !"
        exit 1
    fi  
}

function get_git_ids_4_manifest() {
    check_sb
    
    [ "x$2" = "x" ] && usage
    [ "x$3" = "x" ] && usage
    [ ! -f $2 -o ! -f $3 ] && echo && echo "File not found!" && echo && exit 1
    #GetGitCommitIds=`/ecbuilds/utils/getgitcommits.py $2 $3`
    GetGitCommitIds=`/cs-shared/commit-info/getgitcommits.py $2 $3`
}

function get_git_ids() {
    check_sb

    [ $build2 = "LATEST" ] && build2=`ls -l $build_loc/$release/$build2 | tr -s ' ' | cut -d ' ' -f11`
    [ $build1 = "LATEST" ] && build1=`ls -l $build_loc/$release/$build1 | tr -s ' ' | cut -d ' ' -f11`

    if [ $build1 = $build2 ]; then
        echo
        echo "Unsupported operation !"
        exit 1
    fi

    GetGitCommitIds=`/users/vmahuli/getgitcommits.py $build_loc/$release/$build1/$os/$sku/manifest.xml $build_loc/$release/$build2/$os/$sku/manifest.xml`
}

function parse_commit_ids() {
    echo "GitId                                      When         Author and Description"  >  $WORKSPACE/commit-info.log
    echo "-----                                      ----         ----------------------"  >> $WORKSPACE/commit-info.log
    for repodir in $repos
    do
        if [ -d $WORKSPACE/$repodir ]; then
            cd $WORKSPACE/$repodir
            NO_COMMITS=0
            echo
            echo "Changes from git in $repodir:"
            for gitid in $GetGitCommitIds
            do
                git show $gitid > /dev/null 2>&1
                if [ $? = 0 ]; then
                    string=`git show --pretty=format:"%h %s%n" $gitid -s | cat`
                    git show --pretty=format:"%H    %ar    %an --> %s%n" $gitid -s | cat >> $WORKSPACE/commit-info.log
                    echo $string | sed -e 's/ /   /' | awk '{ print substr($0,1,80)}'
                    NO_COMMITS=`expr $NO_COMMITS \+ 1`
                fi
            done
            [ $NO_COMMITS -eq 0 ] && echo "No commits!"
        fi
    done
}

function main() {
    columns=`tput cols`
    [ "x$1" = "x" ] && usage
    if [ $1 = "-release" -o $1 = "-build" ]; then
        parse_arguments $*
        get_git_ids
        parse_commit_ids
    elif [ $1 = "-manifest" ]; then
        get_git_ids_4_manifest $*
        parse_commit_ids
    else
        usage
    fi
}

main $*
echo
echo Done
