#!/bin/sh

set -e

echo "running post install"
HOST_IP_LIST=`ifconfig | sed -n -e 's/:127\.0\.0\.1 //g' -e 's/ *inet addr:\([0-9.]\+\).*/\1/gp'`
HOSTIP=`echo $HOST_IP_LIST | cut -d' ' -f1`
if [ -f /opt/contrail/contrail_server_manager/IP.txt ];
then
   HOSTIP=$(cat /opt/contrail/contrail_server_manager/IP.txt)
fi

mkdir -p /var/log/contrail/

# Newly added from setup.sh
# Modify webui config file
WEBUI_CONF_FILE=/etc/contrail/config.global.js
SM_CONF_FILE=/usr/src/contrail/contrail-web-server-manager/webroot/common/api/sm.config.js
WEBUI_PATH=/usr/src/contrail/contrail-web-server-manager

set +e
grep "config.featurePkg" $WEBUI_CONF_FILE
if [ $? != 0 ]; then
  echo "config.featurePkg = {};" >> $WEBUI_CONF_FILE
  echo "config.featurePkg.serverManager = {};" >> $WEBUI_CONF_FILE
fi
grep "config.featurePkg.serverManager" $WEBUI_CONF_FILE
if [ $? != 0 ]; then
  echo "config.featurePkg.serverManager = {};" >> $WEBUI_CONF_FILE
fi
grep "config.featurePkg.serverManager.path" $WEBUI_CONF_FILE
if [ $? == 0  ]; then
  sed -i "s|config.featurePkg.serverManager.path = .*|config.featurePkg.serverManager.path = '$WEBUI_PATH';|g" $WEBUI_CONF_FILE
else
  echo "config.featurePkg.serverManager.path = '$WEBUI_PATH';" >> $WEBUI_CONF_FILE
fi
grep "config.featurePkg.serverManager.enable" $WEBUI_CONF_FILE
if [ $? == 0 ]; then
  sed -i "s/config.featurePkg.serverManager.enable = .*/config.featurePkg.serverManager.enable = true;/g" $WEBUI_CONF_FILE
else
  echo "config.featurePkg.serverManager.enable = true;" >> $WEBUI_CONF_FILE
fi
grep "config.orchestration" $WEBUI_CONF_FILE
if [ $? == 0 ]; then
  sed -i "s/config.orchestration = .*/config.orchestration = {};/g" $WEBUI_CONF_FILE
else
  echo "config.orchestration = {};" >> $WEBUI_CONF_FILE
fi
grep "config.orchestration.Manager" $WEBUI_CONF_FILE
if [ $? == 0 ]; then
  sed -i "s/config.orchestration.Manager = .*/config.orchestration.Manager = 'none'/g" $WEBUI_CONF_FILE
else
  echo "config.orchestration.Manager = 'none';" >> $WEBUI_CONF_FILE
fi
grep "config.discoveryService" $WEBUI_CONF_FILE
if [ $? == 0 ]; then
  sed -i "s/config.discoveryService = .*/config.discoveryService = {};/g" $WEBUI_CONF_FILE
else
  echo "config.discoveryService = {};" >> $WEBUI_CONF_FILE
fi
grep "config.discoveryService.enable" $WEBUI_CONF_FILE
if [ $? == 0 ]; then
  sed -i "s/config.discoveryService.enable = .*/config.discoveryService.enable = false;/g" $WEBUI_CONF_FILE
else
  echo "config.discoveryService.enable = false;" >> $WEBUI_CONF_FILE
fi
grep "config.multi_tenancy" $WEBUI_CONF_FILE
if [ $? == 0 ]; then
  sed -i "s/config.multi_tenancy = .*/config.multi_tenancy = {};/g" $WEBUI_CONF_FILE
else
  echo "config.multi_tenancy = {};" >> $WEBUI_CONF_FILE
fi
grep "config.multi_tenancy.enabled" $WEBUI_CONF_FILE
if [ $? == 0 ]; then
  sed -i "s/config.multi_tenancy.enabled = .*/config.multi_tenancy.enabled = false;/g" $WEBUI_CONF_FILE
else
  echo "config.multi_tenancy.enabled = false;" >> $WEBUI_CONF_FILE
fi
grep "module.exports" $WEBUI_CONF_FILE
if [ $? == 0 ]; then
  sed -i "s|module.exports =.*||g" $WEBUI_CONF_FILE
fi
echo "module.exports = config;" >> $WEBUI_CONF_FILE
sed -i "s/config.featurePkg.webController.enable = .*/config.featurePkg.webController.enable = false;/g" $WEBUI_CONF_FILE
sed -i "s/smConfig.sm.server_ip = .*/smConfig.sm.server_ip = '$HOSTIP';/g" $SM_CONF_FILE
sed -i "s/smConfig.sm.server_port = .*/smConfig.sm.server_port = 9001;/g" $SM_CONF_FILE
sed -i "s/smConfig.sm.introspect_ip = .*/smConfig.sm.introspect_ip = '$HOSTIP';/g" $SM_CONF_FILE
sed -i "s/smConfig.sm.introspect_port = .*/smConfig.sm.introspect_port = 8106;/g" $SM_CONF_FILE
set -e

# start redis and supervisord
service redis-server restart
service supervisor restart

# start webui
service supervisor-webui restart
