##
# Ansible playbook for installing contrail build needed packages on server on Ubuntu 12.04.3 LTS.
#


- hosts: contrail 
  user: root
  tasks:
    ##
    # Apt package installation of required software.
    #
    # - script: ../../auto/RPMS/fix-apt.sh
    - copy: src=../../auto/RPMS/sources.list dest=/etc/apt/sources.list
    - command: mkdir ~/dwnld-packages 
    - apt: update_cache=yes
    - apt: pkg=xml-core state=present
    - apt: pkg=python-dev state=present
    - apt: pkg=python-lxml state=present
    - apt: pkg=python-setuptools state=present
    - apt: pkg=python-sphinx state=present
    - apt: pkg=python-pycurl state=present
    - apt_repository: repo='deb http://extras.ubuntu.com/ubuntu precise main' state=present
    - apt_repository: repo='deb-src http://extras.ubuntu.com/ubuntu precise main' state=present
    - apt: pkg=automake state=present
    - apt: pkg=bison state=present
    - apt: pkg=devscripts state=present
    - apt: pkg=fakeroot state=present
    - apt: pkg=libcppunit-dev state=present
    - apt: pkg=libevent-dev state=present
    - apt: pkg=libssl-dev state=present
    - apt: pkg=libtool state=present
    - apt: pkg=libxml2-dev state=present
    - apt: pkg=libxslt1-dev state=present
    - apt: pkg=nfs-common state=present
    - apt: pkg=scons state=present
    - apt: pkg=sysv-rc-conf state=present
    - apt: pkg=xml-core state=present
    - apt: pkg=git state=present
    - apt: pkg=scons state=present
    - apt: pkg=gcc state=present
    - apt: pkg=flex state=present
    - apt: pkg=bison state=present
    - apt: pkg=make state=present
    - apt: pkg=libbz2-dev state=present
    - apt: pkg=g++ state=present
    - apt: pkg=libssl-dev state=present
    - apt: pkg=automake state=present
    - apt: pkg=fakeroot state=present
    - apt: pkg=dh-make state=present
    - apt: pkg=fabric state=present
    - apt: pkg=ant state=present
    - apt: pkg=openjdk-6-jdk state=present
    - apt: pkg=alien state=present
    - apt: pkg=python-eventlet state=present
    - apt: pkg=python-paste state=present
    - apt: pkg=pkg-config state=present
    - apt: pkg=python-dev state=present
    - apt: pkg=python-lxml state=present
    - apt: pkg=python-pip state=present
    - apt: pkg=python-setuptools state=present
    - apt: pkg=python-sphinx state=present
    - apt: pkg=pkg-config state=present
    - apt: pkg=python-pip state=present
    - apt: pkg=python-virtualenv state=present
    - apt: pkg=curl state=present
    - apt: pkg=debhelper state=present
    - apt: pkg=cdbs state=present
    - apt: pkg=libncurses5-dev  state=present
    - apt: pkg=libreadline-dev  state=present
    - apt: pkg=libgnutls-dev state=present
    - apt: pkg=python-all-dev state=present
    - apt: pkg=libavahi-client-dev  state=present
    - apt: pkg=libsasl2-dev state=present
    - apt: pkg=libxen-dev  state=present
    - apt: pkg=open-iscsi-utils  state=present
    - apt: pkg=libgcrypt11-dev state=present
    - apt: pkg=libparted0-dev state=present
    - apt: pkg=libdevmapper-dev  state=present
    - apt: pkg=uuid-dev  state=present
    - apt: pkg=libudev-dev  state=present
    - apt: pkg=libpciaccess-dev  state=present
    - apt: pkg=policykit-1 state=present
    - apt: pkg=libpolkit-gobject-1-dev state=present
    - apt: pkg=libcap-ng-dev  state=present
    - apt: pkg=libnl-3-dev  state=present
    - apt: pkg=libyajl-dev  state=present
    - apt: pkg=libpcap0.8-dev  state=present
    - apt: pkg=libnuma-dev  state=present
    - apt: pkg=radvd  state=present
    - apt: pkg=build-essential  state=present
    - apt: pkg=python-software-properties state=present
    - apt: pkg=libxml2-utils  state=present
    - apt: pkg=libapparmor-dev state=present
    - apt: pkg=linux-headers-3.2.0-51  state=present
    - apt: pkg=linux-headers-3.2.0-58 state=present
    - apt: pkg=linux-headers-3.2.0-51-generic  state=present
    - apt: pkg=linux-headers-3.2.0-58-generic state=present
    - apt: pkg=linux-headers-3.8.0-35 state=present
    - apt: pkg=linux-headers-3.8.0-35-generic state=present
    - apt: pkg=linux-headers-3.8.0-31 state=present
    - apt: pkg=linux-headers-3.8.0-31-generic state=present
    - apt: pkg=libc6:i386 state=present
    - apt: pkg=dnsmasq-base state=present
    
    ##
    # Run the wget commands needed.
    #

    - name: Run wget commands
      command: wget -O /usr/local/bin/repo http://commondatastorage.googleapis.com/git-repo-downloads/repo

    - script: ../../auto/nodejs.sh
 
    ##
    # Set permissions under /bin.
    #
    - name: set permissions
      file: path=/usr/local/bin/repo  mode=0755 

    ##
    # Setup the directory structure and links we need
    - lineinfile: "dest=/etc/fstab regexp=^svl-eng009-cf1.juniper.net:/vol/junosv02/junosv-storage01 line='svl-eng009-cf1.juniper.net:/vol/junosv02/junosv-storage01 /mnt nfs defaults 1 1'"
    - copy: src=../../auto/gitcommits.tgz dest=/tmp
    - script: ../../auto/link.sh 

    ##
    # Copy the contrail build tools
    - copy: src=/mnt/ssd-tools/bin/contrail-build dest=/usr/local/bin/contrail-build
    - copy: src=/mnt/ssd-tools/bin/contrail-create-buildarchive dest=/usr/local/bin/contrail-create-buildarchive
    - copy: src=/mnt/ssd-tools/bin/contrail-manipulate-manifest dest=/usr/local/bin/contrail-manipulate-manifest
    - copy: src=/mnt/ssd-tools/bin/create-base-manifest dest=/usr/local/bin/create-base-manifest
    - copy: src=/mnt/ssd-tools/bin/create-config dest=/usr/local/bin/create-config
    - copy: src=/mnt/ssd-tools/bin/fix-manifest.py dest=/usr/local/bin/fix-manifest.py
    - copy: src=/mnt/ssd-tools/bin/merge-manifest dest=/usr/local/bin/merge-manifest

