echo "Running Preinst for contrail-openstack"
if [ -f /etc/init.d/keystone.initd.supervisord ]; then
    for svc in keystone nova-api nova-scheduler nova-conductor nova-console\
               nova-consoleauth nova-novncproxy glance-api\
               glance-registry cinder-api cinder-scheduler heat-engine heat-api heat-api-cfn\
               barbican-api barbican-worker ; do
        echo "manual" > /etc/init/$svc.override
    done
fi

echo "Preinst for contrail-openstack done"
