#!/bin/bash
#-------------------------
# Testing client utilities
#-------------------------
set -e

HELP_CLIENTS=('nova-xvpvncproxy' 'nova-api')
for client in "${HELP_CLIENTS[@]}"; do
    RET=$($client -h 2>&1 > /dev/null)

    if [[ $RET ]]; then
        echo "ERROR, ${client} is not running"
    fi
done
