#!/bin/bash

set -e

echo "running post install"
DOCKER_IP=`ifconfig docker0 | grep "inet addr" | awk '{print $2}' | cut -d ':' -f 2`
HOST_IP_LIST=`ifconfig | sed -n -e 's/:127\.0\.0\.1 //g' -e "s/:$DOCKER_IP//g" -e 's/ *inet addr:\([0-9.]\+\).*/\1/gp'`
HOST_IP=`echo $HOST_IP_LIST | cut -d' ' -f1`
if [ -f /opt/contrail/contrail_server_manager/IP.txt ];
then
   HOST_IP=$(cat /opt/contrail/contrail_server_manager/IP.txt) 
fi
echo $HOST_IP

HOST_MAC=`ifconfig -a | grep $HOST_IP -b2 | grep HWaddr | awk '{print $5}'`
HOST_FQDN=`hostname -f`
HOST_NAME=`hostname`

SUBNET_ADDRESS=`ip route | grep $HOST_IP | grep -v default | awk '{print $1}' | cut -d '/' -f 1`
SUBNET_GATEWAY=`ip route | grep default | awk '{print $3}'`
SUBNET_MASK=`ifconfig -a | grep $HOST_IP -b4 | grep Mask | awk '{print $5}' | cut -d ':' -f 2`

DOMAIN=`hostname -d`
rel=`lsb_release -r`

# Copy config files into place

# Copy cobbler pxesystem template file for esxi
mv /etc/cobbler/pxe/pxesystem_esxi.template /etc/cobbler/pxe/pxesystem_esxi.template-save
cp /etc/contrail_smgr/cobbler/pxesystem_esxi.template /etc/cobbler/pxe
# Copy cobbler boot.cfg template file for esxi6.5
cp -f /etc/contrail_smgr/cobbler/bootcfg_esxi65.template /etc/cobbler/pxe
# Backup all the distro_signatures files
if [ -f /etc/cobbler/distro_signatures.json ]; then
    mv /etc/cobbler/distro_signatures.json /etc/cobbler/distro_signatures.json-save
fi
if [ -f /var/lib/cobbler/distro_signatures.json ]; then
    mv /var/lib/cobbler/distro_signatures.json /var/lib/cobbler/distro_signatures.json-save
fi
cp /etc/contrail_smgr/cobbler/distro_signatures.json /etc/cobbler/distro_signatures.json
cp /etc/contrail_smgr/cobbler/distro_signatures.json /var/lib/cobbler/distro_signatures.json

cp /etc/contrail_smgr/smgr.conf /etc/apache2/sites-available/

cp -r /etc/contrail_smgr/kickstarts /var/www/html/
cp -r /etc/contrail_smgr/kickstarts/* /var/lib/cobbler/kickstarts/

if [ -f /etc/cobbler/named.template ]; then
    cp /etc/cobbler/named.template /etc/cobbler/named.template.orig
fi
cp /etc/contrail_smgr/cobbler/named.template.u.sample /etc/cobbler/named.template

if [ -f /etc/bind/named.conf.options ]; then
    cp /etc/bind/named.conf.options /etc/bind/named.conf.options.orig
fi
cp /etc/contrail_smgr/cobbler/named.conf.options.u.sample /etc/bind/named.conf.options

#cp /etc/contrail_smgr/sendmail.cf /etc/mail/
mv /etc/ntp.conf /etc/ntp.conf.default
cp /etc/contrail_smgr/ntp.conf.sample /etc/ntp.conf
chown -R puppet:puppet /var/log/contrail-server-manager/provision
# Copying the specific puppet conf files needed for provisioning:
cp /etc/contrail_smgr/puppet/auth.conf /etc/puppet/
cp /etc/contrail_smgr/puppet/autosign.conf /etc/puppet/
cp /etc/contrail_smgr/puppet/fileserver.conf /etc/puppet/
cp /etc/contrail_smgr/puppet/hiera.yaml /etc/puppet/
cp /etc/contrail_smgr/puppet/puppet.conf /etc/puppet/
cp -r /etc/contrail_smgr/puppet/environments /etc/puppet/
cp -u /etc/contrail_smgr/puppet/puppet_init_rd /srv/www/cobbler/aux/puppet

# Stage 3 : Setting configs manually
# Adding server and Public DNS to /etc/resolv.conf if not present
set +e
grep "nameserver $HOST_IP" /etc/resolv.conf
if [ $? != 0 ]; then
  echo "nameserver $HOST_IP" >> /etc/resolv.conf
fi
grep "nameserver 8.8.8.8" /etc/resolv.conf
if [ $? != 0 ]; then
  echo "nameserver 8.8.8.8" >> /etc/resolv.conf
fi
sed -i 's/puppet_auto_setup: 0/puppet_auto_setup: 1/g' /etc/cobbler/settings
sed -i 's/sign_puppet_certs_automatically: 0/sign_puppet_certs_automatically: 1/g' /etc/cobbler/settings
sed -i 's/remove_old_puppet_certs_automatically: 0/remove_old_puppet_certs_automatically: 1/g' /etc/cobbler/settings
sed -i 's/manage_dhcp: 0/manage_dhcp: 1/g' /etc/cobbler/settings
sed -i 's/manage_dns: 0/manage_dns: 1/g' /etc/cobbler/settings
sed -i 's/pxe_just_once: 0/pxe_just_once: 1/g' /etc/cobbler/settings
sed -i 's|webdir: /var/www/cobbler|webdir: /srv/www/cobbler|g' /etc/cobbler/settings
# Set IP address in cobbler settings file
sed -i "s/__\$IPADDRESS__/$HOST_IP/g" /etc/cobbler/settings
sed -i "s/bind_master:.*/bind_master: $HOST_IP/g" /etc/cobbler/settings
sed -i "s/next_server:.*/next_server: $HOST_IP/g" /etc/cobbler/settings
sed -i "s/server:.*/server: $HOST_IP/g" /etc/cobbler/settings
sed -i "s/module = authn_.*/module = authn_testing/g" /etc/cobbler/modules.conf

# DHCP Auto-add the server manager to DHCP HOSTS
sed -i "s/__\$IPADDRESS__/$HOST_IP/g" /opt/contrail/server_manager/generate_dhcp_template.py
sed -i "s/__\$MACADDRESS__/$HOST_MAC/g" /opt/contrail/server_manager/generate_dhcp_template.py
sed -i "s/__\$HOSTFQDN__/$HOST_FQDN/g" /opt/contrail/server_manager/generate_dhcp_template.py
sed -i "s/__\$HOSTNAME__/$HOST_NAME/g" /opt/contrail/server_manager/generate_dhcp_template.py
sed -i "s/__\$SUBNETADDRESS__/$SUBNET_ADDRESS/g" /opt/contrail/server_manager/generate_dhcp_template.py
sed -i "s/__\$SUBNETGATEWAY__/$SUBNET_GATEWAY/g" /opt/contrail/server_manager/generate_dhcp_template.py
sed -i "s/__\$SUBNETMASK__/$SUBNET_MASK/g" /opt/contrail/server_manager/generate_dhcp_template.py
sed -i "s/__\$DOMAIN__/$DOMAIN/g" /opt/contrail/server_manager/generate_dhcp_template.py

sed -i "s/__\$IPADDRESS__/$HOST_IP/g" /etc/contrail_smgr/cobbler/bootup_dhcp.template.u
sed -i "s/__\$MACADDRESS__/$HOST_MAC/g" /etc/contrail_smgr/cobbler/bootup_dhcp.template.u
sed -i "s/__\$HOSTFQDN__/$HOST_FQDN/g" /etc/contrail_smgr/cobbler/bootup_dhcp.template.u
sed -i "s/__\$HOSTNAME__/$HOST_NAME/g" /etc/contrail_smgr/cobbler/bootup_dhcp.template.u
sed -i "s/__\$SUBNETADDRESS__/$SUBNET_ADDRESS/g" /etc/contrail_smgr/cobbler/bootup_dhcp.template.u
sed -i "s/__\$SUBNETGATEWAY__/$SUBNET_GATEWAY/g" /etc/contrail_smgr/cobbler/bootup_dhcp.template.u
sed -i "s/__\$SUBNETMASK__/$SUBNET_MASK/g" /etc/contrail_smgr/cobbler/bootup_dhcp.template.u
sed -i "s/__\$DOMAIN__/$DOMAIN/g" /etc/contrail_smgr/cobbler/bootup_dhcp.template.u

set -e

  # Cobbler config for 14.04
  mkdir -p /etc/apache2/conf-available/
  cp /opt/contrail/contrail_server_manager/cobbler_14.conf /etc/apache2/conf.d/cobbler.conf
  cp /opt/contrail/contrail_server_manager/cobbler_web_14.conf /etc/apache2/conf.d/cobbler_web.conf
  cp /opt/contrail/contrail_server_manager/cobbler_14.conf /etc/cobbler/cobbler.conf
  cp /opt/contrail/contrail_server_manager/cobbler_web_14.conf /etc/cobbler/cobbler_web.conf
  cp /etc/apache2/conf.d/cobbler.conf /etc/apache2/conf-available/
  cp /etc/apache2/conf.d/cobbler_web.conf /etc/apache2/conf-available/
  a2enconf cobbler cobbler_web
  cp -r /srv/www/cobbler /var/www/cobbler
  cp -r /srv/www/cobbler_webui_content /var/www/cobbler_webui_content
  chmod 777 /var/lib/cobbler/webui_sessions/
  # The secret key file can be brought in by SM install - only need to sed the key into settings.py as below
  SECRET_KEY=$(python -c 'import re;from random import choice; import sys; sys.stdout.write(re.escape("".join([choice("abcdefghijklmnopqrstuvwxyz0123456789^&*(-_=+)") for i in range(100)])))')
  sed -i "s/^SECRET_KEY = .*/SECRET_KEY = '${SECRET_KEY}'/" /usr/share/cobbler/web/settings.py
a2ensite smgr.conf
a2enmod proxy
a2enmod proxy_http
a2enmod wsgi
a2dismod mpm_event
a2enmod mpm_worker

update-rc.d contrail-server-manager defaults
# Set IP address in server manager configuration file.
sed -i "s/__\$IPADDRESS__/$HOST_IP/g" /opt/contrail/server_manager/sm-config.ini
sed -i "s/127.0.0.1/$HOST_IP/g" /opt/contrail/server_manager/sm-config.ini
# Set IP Address in smgr_dhcp_event.py DHCP hook.
sed -i "s/__\$IPADDRESS__/$HOST_IP/g" /opt/contrail/server_manager/smgr_dhcp_event.py
sed -i "s/cobbler_username         = cobbler/cobbler_username         = testing/g" /opt/contrail/server_manager/sm-config.ini
sed -i "s/cobbler_password         = cobbler/cobbler_password         = testing/g" /opt/contrail/server_manager/sm-config.ini
#sed -i 's:"/var/named":"/var/cache/bind":g' /etc/cobbler/named.template
#sed -i 's:/var/named/data:/var/cache/bind:g' /etc/cobbler/named.template
#sed -i 's:data/named.run:named.run:g' /etc/cobbler/named.template

set +e
POSTFIX_CHECK=$(dpkg -l | grep postfix)
if [ "$INSTALLED" != "" ]; then
    service postfix stop
fi
set -e
service sendmail restart

pushd /var/www/html/thirdparty_packages
dpkg-scanpackages . | gzip -9c > Packages.gz
popd

pushd /var/www/html/thirdparty_packages_ubuntu_1604
dpkg-scanpackages . | gzip -9c > Packages.gz
popd

for f in /etc/cobbler/power/*.template; do
if ! grep -q '#for \$fact' $f; then
cat << EOT >> $f
#for \$fact, \$value in  \$ks_meta.items()
  #if \$fact=='ipmi_interface' and \$value == 'lanplus'
    lanplus
  #elif \$fact=='ipmi_interface' and \$value=='lan'
    lan
  #else
    #pass
  #end if
#end for
EOT
fi
done

update-rc.d apache2 defaults
update-rc.d xinetd defaults
update-rc.d cobblerd defaults
service apache2 restart
service xinetd restart
service cobblerd restart
