#!/bin/bash

set -e


echo "running post install"

cp -r /etc/contrail_smgr/cobbler /etc/
cp -r /etc/contrail_smgr/puppet /etc/
if [ -f /etc/cobbler/distro_signatures.json ]; then
    mv /etc/cobbler/distro_signatures.json /etc/cobbler/distro_signatures.json-save
fi
if [ -f /var/lib/cobbler/distro_signatures.json ]; then
    mv /var/lib/cobbler/distro_signatures.json /var/lib/cobbler/distro_signatures.json-save
fi
cp /etc/contrail_smgr/cobbler/distro_signatures.json-esxi55 /etc/cobbler/distro_signatures.json
cp /etc/contrail_smgr/cobbler/distro_signatures.json-esxi55 /var/lib/cobbler/distro_signatures.json
cd /etc/contrail_smgr/contrail-centos-repo
createrepo .
cd /etc/contrail_smgr/contrail-redhat-repo
createrepo .

# Copy cobbler boot.cfg template file for esxi5.5
cp -f /etc/contrail_smgr/cobbler/bootcfg_esxi55.template /etc/cobbler/pxe

# Copy cobbler pxesystem template file for esxi
mv /etc/cobbler/pxe/pxesystem_esxi.template /etc/cobbler/pxe/pxesystem_esxi.template-save
cp /etc/contrail_smgr/cobbler/pxesystem_esxi.template /etc/cobbler/pxe
#cp /etc/contrail_smgr/cobbler/dhcp.template.u /etc/cobbler/dhcp.template
cp /etc/contrail_smgr/cobbler/named.template.u /etc/cobbler/named.template
cp /etc/contrail_smgr/cobbler/named.conf.options.u /etc/bind/named.conf.options

mkdir -p /var/www/html
mkdir -p /var/www/html/kickstarts
cp -r /etc/contrail_smgr/kickstarts /var/www/html/
mkdir -p /var/www/html/contrail
mkdir -p /var/www/html/contrail/config_file
mkdir -p /var/www/html/contrail/images
mkdir -p /var/log/contrail-server-manager
mkdir -p /etc/mail/
cp /etc/contrail_smgr/sendmail.cf /etc/mail/

# Saving and replacing default NTP configuration (Server Manager node acts as NTP Server for Cluster)
mv /etc/ntp.conf /etc/ntp.conf.default
cp /etc/contrail_smgr/ntp.conf /etc/ntp.conf

#cp /usr/bin/server_manager/dhcp.template /etc/cobbler/
#cp -r /usr/bin/server_manager/kickstarts /var/www/html/
mkdir -p /var/www/html/contrail
mkdir -p /var/www/html/thirdparty_packages

cp -u /etc/puppet/puppet_init_rd /srv/www/cobbler/aux/puppet
easy_install argparse
easy_install paramiko
easy_install pycrypto
easy_install ordereddict

mkdir -p /etc/contrail_smgr/images/

sed -i 's/puppet_auto_setup: 0/puppet_auto_setup: 1/g' /etc/cobbler/settings
sed -i 's/sign_puppet_certs_automatically: 0/sign_puppet_certs_automatically: 1/g' /etc/cobbler/settings

sed -i 's/remove_old_puppet_certs_automatically: 0/remove_old_puppet_certs_automatically: 1/g' /etc/cobbler/settings
sed -i 's/manage_dhcp: 0/manage_dhcp: 1/g' /etc/cobbler/settings
sed -i 's/manage_dns: 0/manage_dns: 1/g' /etc/cobbler/settings
sed -i 's|webdir: /var/www/cobbler|webdir: /srv/www/cobbler|g' /etc/cobbler/settings
rel=`lsb_release -r`
if [[ "$rel" == *"14.04"* ]]; then
    echo "Not seding files for 14.04"
else
    sed -i ':a;N;$!ba;s:DocumentRoot /var/www\n:DocumentRoot /var/www/html\n:g' /etc/apache2/sites-available/default
    sed -i 's:<Directory /var/www/>:<Directory /var/www/html/>:g' /etc/apache2/sites-available/default
fi

HOST_IP_LIST=`ifconfig | sed -n -e 's/:127\.0\.0\.1 //g' -e 's/ *inet addr:\([0-9.]\+\).*/\1/gp'`
HOST_IP=`echo $HOST_IP_LIST | cut -d' ' -f1`
if [ -f /opt/contrail/contrail_server_manager/IP.txt ];
then
   HOST_IP=$(cat /opt/contrail/contrail_server_manager/IP.txt) 
fi
echo $HOST_IP

# Set IP address in cobbler settings file
sed -i "s/__\$IPADDRESS__/$HOST_IP/" /etc/cobbler/settings
update-rc.d contrail-server-manager defaults
#/sbin/chkconfig --add contrail-server-manager
sed -i "s/module = authn_.*/module = authn_testing/g" /etc/cobbler/modules.conf

# Set IP address in server manager configuration file.
sed -i "s/__\$IPADDRESS__/$HOST_IP/g" /opt/contrail/server_manager/sm-config.ini

# Set IP Address in smgr_dhcp_event.py DHCP hook.
sed -i "s/__\$IPADDRESS__/$HOST_IP/g" /opt/contrail/server_manager/smgr_dhcp_event.py

sed -i "s/cobbler_username         = cobbler/cobbler_username         = testing/g" /opt/contrail/server_manager/sm-config.ini
sed -i "s/cobbler_password         = cobbler/cobbler_password         = testing/g" /opt/contrail/server_manager/sm-config.ini
#sed -i 's:"/var/named":"/var/cache/bind":g' /etc/cobbler/named.template
#sed -i 's:/var/named/data:/var/cache/bind:g' /etc/cobbler/named.template
#sed -i 's:data/named.run:named.run:g' /etc/cobbler/named.template

service apache2 restart
service xinetd restart
service cobblerd restart

POSTFIX_CHECK=$(dpkg -l \grep postfix)
if [ "$INSTALLED" != "" ]; then
    service postfix stop
fi
service sendmail restart

#chkconfig apache2 on
#chkconfig puppetmaster on
#chkconfig contrail_smgrd on

cd /var/www/html/thirdparty_packages
dpkg-scanpackages . | gzip -9c > Packages.gz

update-rc.d apache2 defaults
update-rc.d xinetd defaults
update-rc.d cobblerd defaults
update-rc.d puppetmaster defaults
