#!/bin/bash -x

[ "$#" == "0" ] || ( echo $"Bad invocation of $0" && exit 1 )
base=$1
shift

source /opt/contrail/api-venv/bin/activate
python /opt/contrail/api-venv/lib/python2.7/site-packages/${base} $*
ret=$?
deactivate

exit $ret
