#!/bin/bash

line_num=`cat /etc/apt/sources.list | grep -n contrail_install_repo | cut -d ':' -f1`
sed -i 's%deb file\:\/opt\/contrail\/contrail_install_repo \.\/%%' /etc/apt/sources.list
sed -i ''$line_num'{/^$/d}' /etc/apt/sources.list

cd /opt/contrail/contrail_install_repo
dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz

echo "You may need to run \"apt-get update\" after de-installing the package..."

rm -f /opt/contrail/.contrail_packages
