#!/bin/sh
is_systemd=
if [ -d /run/systemd/system ]; then
   is_systemd=1
fi

if [ "$1" = "configure" ]; then
    echo "Running Postinst for contrail-openstack-webui install.."

    if [ -z "$2" ]; then
        i=0
        while : ; do
            sudo service opscenterd status
            if [ $? -eq 0 ] ; then
                break
            fi
            i=$(($i+1))
            if [ $i -gt 10 ] ; then
                echo "Error: postinst contrail-openstack-webui, expected opscenterd to be running"
                break
            fi
            sleep 3
        done
        sudo service opscenterd stop
        i=0
        while : ; do
            ps auxw | grep -Eq "opscenter\.pid" 2>/dev/null
            if [ $? -ne 0 ] ; then
                break
            fi
            i=$(($i+1))
            if [ $i -gt 5 ] ; then
                kill `ps auxw | grep -E "opscenter\.pid" | grep -v grep | awk '{print $2}'` > /dev/null 2>&1
                break
            fi
            sleep 2
        done
    fi
    if [ -n "$is_systemd" ]; then
        sudo systemctl disable opscenterd
    else
        sudo update-rc.d opscenterd disable
    fi
fi
echo "Postinst for contrail-openstack-webui done"
