
- hosts: contrail
  user: root
  tasks:
    - lineinfile: "dest=/etc/sudoers regexp=^mganley insertafter=^root line='mganley ALL=(ALL)       NOPASSWD: ALL'"
    - lineinfile: "dest=/etc/sudoers regexp='^Defaults[ ,       ]*requiretty'  line='#Defaults    requiretty'"

     

